##This is Heart Disease prediction model trained by Anshika Gaur, The model we have used is Random Forest Classifier and the dataset is from kaggle, here is the link
https://www.kaggle.com/datasets/emmydesign/cardiovascular-disease-prediction-dataset

In [31]:
import pandas as pd

In [19]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [47]:
df = pd.read_csv('/content/drive/MyDrive/HeartDiseasePrediction/cardiovascular_disease.csv')
df

,PatientID,Age,Gender,BMI,Smoking,Alcohol,FamilyHistory,SystolicBP,DiastolicBP,HeartRate,Cholesterol,Glucose,OxygenSaturation,HRV,RRInterval,QTInterval,QRSDuration,PulseTransitTime,PPGAmplitude,DiseaseLabel
0,P0001,59,Male,28.8,No,No,No,110,78,76,225,93,97.1,56,791,395,80,236,1.96,0
1,P0002,50,Male,22.8,No,Moderate,Yes,139,74,70,241,125,97.4,52,895,365,92,240,1.63,0
2,P0003,61,Female,28.3,No,No,No,144,73,77,215,90,98.2,65,775,370,85,201,1.92,0
3,P0004,73,Female,34.1,No,Moderate,No,142,88,76,230,144,98.5,49,790,415,92,227,1.22,1
4,P0005,49,Male,29.8,Yes,No,No,145,89,77,245,131,96.8,37,758,374,101,198,1.82,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,P0996,48,Male,28.3,No,Moderate,Yes,138,77,71,198,116,98.5,76,865,383,95,195,1.33,0
996,P0997,77,Male,19.8,No,Moderate,No,140,85,63,208,104,97.4,47,968,394,100,199,1.55,1
997,P0998,61,Male,22.7,No,No,No,145,87,58,193,103,97.4,66,1004,390,91,207,1.74,1
998,P0999,44,Male,40.0,No,High,No,130,80,90,221,106,98.2,58,583,386,91,204,1.02,0
999,P1000,60,Male,25.9,No,No,No,144,87,64,221,121,97.9,71,950,386,106,226,2.10,0

In [48]:
df = df.drop(columns='PatientID')
df

,Age,Gender,BMI,Smoking,Alcohol,FamilyHistory,SystolicBP,DiastolicBP,HeartRate,Cholesterol,Glucose,OxygenSaturation,HRV,RRInterval,QTInterval,QRSDuration,PulseTransitTime,PPGAmplitude,DiseaseLabel
0,59,Male,28.8,No,No,No,110,78,76,225,93,97.1,56,791,395,80,236,1.96,0
1,50,Male,22.8,No,Moderate,Yes,139,74,70,241,125,97.4,52,895,365,92,240,1.63,0
2,61,Female,28.3,No,No,No,144,73,77,215,90,98.2,65,775,370,85,201,1.92,0
3,73,Female,34.1,No,Moderate,No,142,88,76,230,144,98.5,49,790,415,92,227,1.22,1
4,49,Male,29.8,Yes,No,No,145,89,77,245,131,96.8,37,758,374,101,198,1.82,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,48,Male,28.3,No,Moderate,Yes,138,77,71,198,116,98.5,76,865,383,95,195,1.33,0
996,77,Male,19.8,No,Moderate,No,140,85,63,208,104,97.4,47,968,394,100,199,1.55,1
997,61,Male,22.7,No,No,No,145,87,58,193,103,97.4,66,1004,390,91,207,1.74,1
998,44,Male,40.0,No,High,No,130,80,90,221,106,98.2,58,583,386,91,204,1.02,0
999,60,Male,25.9,No,No,No,144,87,64,221,121,97.9,71,950,386,106,226,2.10,0

In [57]:
df['Gender'] = df['Gender'].map({'Male':1,'Female':0})
df['Alcohol'] = df['Alcohol'].map({'Moderate':1,'No':0,'High':2})
df['Smoking'] = df['Smoking'].map({'Yes':1,'No':0})
df['FamilyHistory'] = df['FamilyHistory'].map({'Yes':1,'No':0})

In [58]:
df

,Age,Gender,BMI,Smoking,Alcohol,FamilyHistory,SystolicBP,DiastolicBP,HeartRate,Cholesterol,Glucose,OxygenSaturation,HRV,RRInterval,QTInterval,QRSDuration,PulseTransitTime,PPGAmplitude,DiseaseLabel
0,59,1,28.8,0,0,0,110,78,76,225,93,97.1,56,791,395,80,236,1.96,0
1,50,1,22.8,0,1,1,139,74,70,241,125,97.4,52,895,365,92,240,1.63,0
2,61,0,28.3,0,0,0,144,73,77,215,90,98.2,65,775,370,85,201,1.92,0
3,73,0,34.1,0,1,0,142,88,76,230,144,98.5,49,790,415,92,227,1.22,1
4,49,1,29.8,1,0,0,145,89,77,245,131,96.8,37,758,374,101,198,1.82,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,48,1,28.3,0,1,1,138,77,71,198,116,98.5,76,865,383,95,195,1.33,0
996,77,1,19.8,0,1,0,140,85,63,208,104,97.4,47,968,394,100,199,1.55,1
997,61,1,22.7,0,0,0,145,87,58,193,103,97.4,66,1004,390,91,207,1.74,1
998,44,1,40.0,0,2,0,130,80,90,221,106,98.2,58,583,386,91,204,1.02,0
999,60,1,25.9,0,0,0,144,87,64,221,121,97.9,71,950,386,106,226,2.10,0

In [59]:
gendercount = df['Gender'].value_counts()
print(gendercount)

Gender
1    509
0    491
Name: count, dtype: int64

In [60]:
df.isnull().sum()

Age                 0
Gender              0
BMI                 0
Smoking             0
Alcohol             0
FamilyHistory       0
SystolicBP          0
DiastolicBP         0
HeartRate           0
Cholesterol         0
Glucose             0
OxygenSaturation    0
HRV                 0
RRInterval          0
QTInterval          0
QRSDuration         0
PulseTransitTime    0
PPGAmplitude        0
DiseaseLabel        0
dtype: int64

In [61]:
df.describe()

,Age,Gender,BMI,Smoking,Alcohol,FamilyHistory,SystolicBP,DiastolicBP,HeartRate,Cholesterol,Glucose,OxygenSaturation,HRV,RRInterval,QTInterval,QRSDuration,PulseTransitTime,PPGAmplitude,DiseaseLabel
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.0000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,52.294000,0.509000,26.856200,0.213000,0.749000,0.253000,139.298000,81.054000,75.116000,226.124000,107.366000,97.868100,57.1300,810.597000,389.362000,91.195000,211.378000,1.569270,0.442000
std,13.553939,0.500169,4.608027,0.409633,0.653013,0.434948,15.778852,9.312992,8.477996,29.406519,17.978244,0.864002,11.8869,102.218458,22.324501,8.845859,15.412614,0.280514,0.496873
min,20.000000,0.000000,17.500000,0.000000,0.000000,0.000000,95.000000,58.000000,48.000000,126.000000,65.000000,95.300000,18.0000,544.000000,320.000000,70.000000,158.000000,0.350000,0.000000
25%,43.000000,0.000000,23.675000,0.000000,0.000000,0.000000,129.000000,74.750000,69.000000,206.000000,95.000000,97.300000,49.0000,737.750000,375.000000,85.000000,201.000000,1.400000,0.000000
50%,52.000000,1.000000,27.000000,0.000000,1.000000,0.000000,139.000000,81.000000,75.000000,225.000000,107.000000,97.900000,57.0000,803.000000,389.000000,91.000000,212.000000,1.610000,0.000000
75%,61.000000,1.000000,30.100000,0.000000,1.000000,1.000000,150.000000,88.000000,81.000000,246.000000,120.000000,98.400000,65.0000,874.000000,404.000000,97.000000,222.000000,1.760000,1.000000
max,89.000000,1.000000,41.800000,1.000000,2.000000,1.000000,184.000000,113.000000,107.000000,311.000000,164.000000,100.000000,91.0000,1261.000000,468.000000,121.000000,260.000000,2.270000,1.000000

In [62]:
from sklearn.model_selection import train_test_split

x = df.drop(columns='DiseaseLabel')
y = df["DiseaseLabel"]
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [63]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()
model.fit(x_train, y_train)

RandomForestClassifier()

In [64]:
from sklearn.metrics import accuracy_score

y_pred = model.predict(x_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.77

In [65]:
from sklearn.tree import DecisionTreeClassifier

model2 = DecisionTreeClassifier()
model2.fit(x_train, y_train)
y_pred2 = model2.predict(x_test)
accuracy2 = accuracy_score(y_test, y_pred2)
print("Accuracy:", accuracy2)

Accuracy: 0.755

In [66]:
from sklearn.svm import SVC
model3 = SVC()
model3.fit(x_train, y_train)
y_pred3 = model3.predict(x_test)
accuracy3 = accuracy_score(y_test, y_pred3)
print("Accuracy:", accuracy3)

Accuracy: 0.675

In [67]:
from sklearn.neighbors import KNeighborsClassifier
model4 = KNeighborsClassifier()
model4.fit(x_train, y_train)
y_pred4 = model4.predict(x_test)
accuracy4 = accuracy_score(y_test, y_pred4)
print("Accuracy:", accuracy4)

Accuracy: 0.745

In [68]:
from sklearn.linear_model import LogisticRegression
model5 = LogisticRegression()
model5.fit(x_train, y_train)
y_pred5 = model5.predict(x_test)
accuracy5 = accuracy_score(y_test, y_pred5)
print("Accuracy:", accuracy5)

Accuracy: 0.745

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [73]:
columns = x_train.columns
print(columns)
firstrow = [73,0,34.1,0,1,0,142,88,76,230,144,98.5,49,790,415,92,227,1.22,]
mydataset = pd.DataFrame([firstrow],columns=columns)
prediction = model.predict(mydataset)
print("output",prediction)

Index(['Age', 'Gender', 'BMI', 'Smoking', 'Alcohol', 'FamilyHistory',
       'SystolicBP', 'DiastolicBP', 'HeartRate', 'Cholesterol', 'Glucose',
       'OxygenSaturation', 'HRV', 'RRInterval', 'QTInterval', 'QRSDuration',
       'PulseTransitTime', 'PPGAmplitude'],
      dtype='object')
output [1]